-- Migration 0002: seed 16 Cores + global admin settings
-- SHA-256('PEOPLE-05152005') = computed below at insert time via pgcrypto digest()
create extension if not exists "pgcrypto";

insert into public.cores (id, name, tagline, description, rules, accent_color, gradient, layout, icon_name) values
('opium-core','Opium Core','Dark avant-garde aesthetics, subterranean fashion, and industrial minimalism.','A hyper-curated space dedicated to dark ambient subcultures, industrial design, silhouette experimentation, soundscapes, and rebellious visual poetry. Opium Core studies the architecture of shadow: brutalist garments, monochrome palettes, distorted sampling, concrete interiors, and the philosophy of refusal.',array['No low-effort moodboard spam — annotate every reference with intent.','Credit photographers, designers, and producers.','Critique the work, never harass the creator.','No fast-fashion hauls; deconstruction over consumption.'],'#6d778b','linear-gradient(135deg, #2b313b, #6d778b)','grid','Moon'),
('politics-core','Politics Core','Uncensored political analysis, civic critique, and governance discourse.','A fearless forum for dismantling systemic propaganda, dissecting policy, scrutinizing leadership, and proposing radical democratic transparency. Politics Core demands receipts: primary sources, voting records, budget lines, and constitutional clauses.',array['Cite sources for factual claims; screenshots need links.','No ethnic or religious slurs — attack policies, not peoples.','Distinguish opinion from reporting.','No campaign spam or astroturfing.'],'#8b97ad','linear-gradient(135deg, #4f5869, #8b97ad)','compact','Landmark'),
('religion-core','Religion Core','Theological deconstruction, spiritual inquiry, and existential doctrine.','An intellectual sanctuary for questioning dogma, analyzing ancient texts, exploring faith, secularism, and spiritual liberation without fear of ostracization.',array['No blasphemy-baiting or proselytizing raids.','Treat sacred texts and sincere doubt with equal rigor.','Academic tone: argue exegesis, not identity.','No doom prophecy or miracle-sale scams.'],'#6d778b','linear-gradient(135deg, #3d444f, #8b97ad)','grid','BookOpen'),
('feminism-core','Feminism Core','Autonomy, equality, structural critique, and women''s liberation.','Dedicated to dismantling patriarchal power structures, advancing body autonomy, economic self-determination, and intersectional gender equity.',array['Center women''s lived experience; no sealioning.','No misogyny, victim-blaming, or body-shaming.','Intersectionality is non-negotiable.','Share resources, not just outrage.'],'#8b97ad','linear-gradient(135deg, #6d778b, #c3cad5)','grid','Venus'),
('race-core','Race Core','Post-colonial studies, racial identity, systemic bias, and global pan-Africanism.','An analytical space probing historical racial constructs, institutional racism, pan-African solidarity, and social justice.',array['No racial slurs or biological essentialism.','Peer-reviewed or primary sources preferred.','No trauma-dumping without content warnings.','Amplify, don''t speak over, affected communities.'],'#4f5869','linear-gradient(135deg, #0f1319, #6d778b)','compact','Globe'),
('egalitarian-core','Egalitarian Core','Equal rights, class consciousness, and universal human dignity.','Advocating for the total elimination of class exploitation, systemic privilege, inequality, and institutional disenfranchisement.',array['No classist contempt or poverty-shaming.','Proposals must consider the most precarious first.','Data over anecdote when debating systems.','No partisan campaign material.'],'#6d778b','linear-gradient(135deg, #4f5869, #a3adbf)','grid','Scale'),
('renaissance-core','Renaissance Core','Blueprint for structural change, national transformation, and civic awakening in Nigeria.','An actionable think-tank devoted to reinventing Nigerian infrastructure, judicial reform, economic sovereignty, youth empowerment, and socio-political renewal. Every critique must carry a costed alternative.',array['Nigeria-first, tribe-last: no ethnic bigotry.','Every problem post should propose a mechanism.','Verify statistics with NBS, CBN, or equivalent sources.','No praise-singing of politicians without records.'],'#8b97ad','linear-gradient(135deg, #272c34, #8b97ad)','grid','Sunrise'),
('lgbtq-core','LGBTQ+ Core','Queer expression, identity rights, safety, and community solidarity.','A safe, pseudonymous sanctuary for gender diversity, sexual orientation freedom, support systems, and advocacy.',array['Absolute zero tolerance for homophobia or transphobia.','Never out anyone or request identifying details.','Content warnings on sensitive trauma topics.','No fetishizing or invasive curiosity.'],'#a3adbf','linear-gradient(135deg, #6d778b, #e2e6ec)','grid','Rainbow'),
('fashion-core','Fashion Core','Sartorial theory, textile art, streetwear, and subculture identity.','Exploring garment design, sustainable style, cultural attire, runway critiques, and individual self-expression through attire.',array['Include garment details on fit posts.','No counterfeit promotion.','Respect cultural garments; no costume mockery.','Sustainable critique over brand worship.'],'#8b97ad','linear-gradient(135deg, #3d444f, #c3cad5)','grid','Shirt'),
('philosophy-core','Philosophy Core','Epistemology, metaphysics, ethics, and rigorous intellectual inquiry.','A domain for debating existentialism, stoicism, morality, consciousness, and the foundational frameworks of human thought.',array['Steelman opposing views before rebuttal.','Cite the text: edition, section, or paragraph.','No pseudo-profundity without argument.','Stay on the thesis; no ad hominem.'],'#6d778b','linear-gradient(135deg, #0a0c10, #4f5869)','compact','Brain'),
('critical-thinking-core','Critical Thinking Core','Logic, cognitive fallacies, media literacy, and empirical reasoning.','Sharp intellectual dissection aimed at spotting disinformation, logical fallacies, emotional manipulation, and cognitive bias in public discourse.',array['Name the fallacy and show your work.','Link original sources, not screenshots alone.','Update publicly when proven wrong.','No conspiracism without falsifiable evidence.'],'#4f5869','linear-gradient(135deg, #272c34, #6d778b)','compact','Microscope'),
('movies-core','Movies Core','Cinematic critique, auteur cinema, narrative analysis, and film theory.','In-depth discussion on cinematography, narrative structures, directorial visions, and the cultural impact of cinema.',array['Spoiler tags for films under 2 years old.','No piracy links; discuss legal access.','Critique craft, not just plot.','No review-bombing campaigns.'],'#8b97ad','linear-gradient(135deg, #0f1319, #8b97ad)','grid','Clapperboard'),
('series-core','Series Core','Serialized storytelling, television drama, world-building, and episode breakdowns.','Analyzing episodic storytelling, character trajectories, writing rooms, and television culture.',array['Episode-tag spoilers strictly.','No leaks of unreleased episodes.','Separate actor from character in critique.','Cross-posts welcome with tags.'],'#6d778b','linear-gradient(135deg, #3d444f, #6d778b)','grid','Tv'),
('life-core','Life Core','Realities, personal confessions, mental endurance, and everyday truths.','An unfiltered space for sharing raw human experiences, mental health struggles, life lessons, financial survival, and personal growth.',array['Radical kindness: no mocking vulnerability.','No medical diagnosis; suggest professionals.','Content warnings for self-harm, abuse, loss.','No financial scams or begging links.'],'#a3adbf','linear-gradient(135deg, #4f5869, #c3cad5)','compact','Heart'),
('cartoon-core','Cartoon Core','Animation history, subversion in visual storytelling, and classic nostalgia.','Celebrating western animation, satirical cartoons, character design, and the artistic evolution of animated media.',array['Credit studios, boards artists, and voice actors.','Nostalgia welcome, but add analysis.','No full-episode re-uploads.','Keep kids''-show critique age-aware.'],'#8b97ad','linear-gradient(135deg, #272c34, #a3adbf)','grid','Palette'),
('anime-core','Anime Core','Otaku subculture, animation craft, manga discourse, and thematic breakdowns.','Deep-dive discussions on anime series, manga lore, studio animation techniques, and philosophical themes in Japanese animation.',array['Spoiler-tier your posts.','No pirate-site links; use legal source names.','Sakuga clips need animator/studio credit when known.','Respect sub vs dub preferences.'],'#6d778b','linear-gradient(135deg, #0a0c10, #8b97ad)','grid','Sparkles')
on conflict (id) do update set
  name = excluded.name, tagline = excluded.tagline, description = excluded.description,
  rules = excluded.rules, accent_color = excluded.accent_color, gradient = excluded.gradient,
  layout = excluded.layout, icon_name = excluded.icon_name;

-- Global admin settings (hash of PEOPLE-05152005 installed by app if missing)
insert into public.admin_settings (id, master_passkey_hash, authorized_roster)
values ('global', encode(digest('PEOPLE-05152005','sha256'),'hex'), '{}')
on conflict (id) do nothing;
